{{- if .Values.general.debugZero.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debugZero.backend.name" . }}
  labels:
    app: {{ include "debugZero.backend.name" . }}
spec:
  strategy:
      type: {{ .Values.deployments.debugZero.backend.rollout_strategy }}
  {{- if not .Values.deployments.debugZero.backend.hpa.enabled }}
  replicas: {{ .Values.deployments.debugZero.backend.replicas }}
  {{- end }}
  selector:
    matchLabels:
     app: {{ include "debugZero.backend.name" . }}
  template:
    metadata:
      {{- with .Values.deployments.debugZero.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "debugZero.backend.name" . }}
        {{- with .Values.deployments.debugZero.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.deployments.debugZero.backend.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{ toYaml .Values.deployments.debugZero.backend.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "debugZero.backend.serviceAccountName" . }}
      {{- with .Values.deployments.debugZero.backend.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      {{- if .Values.secrets.defaults.dockerhub_config.existingSecret }}
        - name: {{ .Values.secrets.defaults.dockerhub_config.existingSecret }}
      {{- else }}
        - name: {{ include "secrets.dockerhub.name" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.deployments.debugZero.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "debugZero.backend.name" . }}
          securityContext: {{- include "debugZero.backend.containerSecurityContext" . | indent 12 }}
          image: "{{ .Values.deployments.debugZero.backend.image.repository }}:{{ .Values.deployments.debugZero.backend.image.tag }}"
          imagePullPolicy: {{ .Values.deployments.debugZero.backend.image.pullPolicy }}
          {{- include "debugZero.backend.env" . | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.deployments.debugZero.backend.service.port }}
              protocol: TCP
          {{- with .Values.deployments.debugZero.backend.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}              
          {{- if and .Values.deployments.debugZero.backend.livenessProbe.enabled .Values.deployments.debugZero.backend.livenessProbe.enabled }}
          livenessProbe:
            {{- if .Values.deployments.debugZero.backend.livenessProbe.httpGet }}
            httpGet:
              path: {{ .Values.deployments.debugZero.backend.livenessProbe.httpGet.path }}
              port: {{ .Values.deployments.debugZero.backend.livenessProbe.httpGet.port }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.livenessProbe.initialDelaySeconds }}
            initialDelaySeconds: {{ .Values.deployments.debugZero.backend.livenessProbe.initialDelaySeconds }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.livenessProbe.periodSeconds }}
            periodSeconds: {{ .Values.deployments.debugZero.backend.livenessProbe.periodSeconds }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.livenessProbe.timeoutSeconds }}
            timeoutSeconds: {{ .Values.deployments.debugZero.backend.livenessProbe.timeoutSeconds }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.livenessProbe.failureThreshold }}
            failureThreshold: {{ .Values.deployments.debugZero.backend.livenessProbe.failureThreshold }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.livenessProbe.successThreshold }}
            successThreshold: {{ .Values.deployments.debugZero.backend.livenessProbe.successThreshold }}
            {{- end }}
          {{- end }}
          {{- if and .Values.deployments.debugZero.backend.readinessProbe.enabled .Values.deployments.debugZero.backend.readinessProbe.enabled }}
          readinessProbe:
            {{- if .Values.deployments.debugZero.backend.readinessProbe.httpGet }}
            httpGet:
              path: {{ .Values.deployments.debugZero.backend.readinessProbe.httpGet.path }}
              port: {{ .Values.deployments.debugZero.backend.readinessProbe.httpGet.port }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.readinessProbe.initialDelaySeconds }}
            initialDelaySeconds: {{ .Values.deployments.debugZero.backend.readinessProbe.initialDelaySeconds }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.readinessProbe.periodSeconds }}
            periodSeconds: {{ .Values.deployments.debugZero.backend.readinessProbe.periodSeconds }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.readinessProbe.timeoutSeconds }}
            timeoutSeconds: {{ .Values.deployments.debugZero.backend.readinessProbe.timeoutSeconds }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.readinessProbe.failureThreshold }}
            failureThreshold: {{ .Values.deployments.debugZero.backend.readinessProbe.failureThreshold }}
            {{- end }}
            {{- if .Values.deployments.debugZero.backend.readinessProbe.successThreshold }}
            successThreshold: {{ .Values.deployments.debugZero.backend.readinessProbe.successThreshold }}
            {{- end }}
          {{- end }}
          resources:
            requests:
              cpu: {{ .Values.deployments.debugZero.backend.resources.cpu }}
              memory: {{ .Values.deployments.debugZero.backend.resources.memory }}
            limits:
              cpu: {{ .Values.deployments.debugZero.backend.resources.cpu }}
              memory: {{ .Values.deployments.debugZero.backend.resources.memory }}
          envFrom:
            - secretRef:
                name: {{ include "secrets.debugZero.backend.name" . }}
      {{- if .Values.general.tolerations }}
      tolerations:
        {{ toYaml .Values.general.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.general.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.general.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.deployments.debugZero.backend.affinity }}
      affinity:
        {{ toYaml .Values.deployments.debugZero.backend.affinity | nindent 8 }}
      {{- end }}
{{- end -}}