{{- if .Values.general.debugZero.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "debugZero.backend.name" . }}
  {{- with .Values.deployments.debugZero.backend.service.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{ end }}
  {{- with .Values.deployments.debugZero.backend.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  type: {{ .Values.deployments.debugZero.backend.service.type }}
  ports:
    - port: {{ .Values.deployments.debugZero.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "debugZero.backend.name" . }}
{{- end }}